data = '''
<?xml version="1.0" encoding="ISO-8859-1"?>
<Respuesta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/Respuesta.xsd">
  <Personas>
    <Persona>
      <Encabezado>
        <FolioConsultaOtorgante>1695217</FolioConsultaOtorgante>
        <ClaveOtorgante>0000091008</ClaveOtorgante>
        <ExpedienteEncontrado>1</ExpedienteEncontrado>
        <FolioConsulta>775297075</FolioConsulta>
      </Encabezado>
      <Nombre>
        <ApellidoPaterno>BETANZOS</ApellidoPaterno>
        <ApellidoMaterno>CRUZ</ApellidoMaterno>
        <ApellidoAdicional/>
        <Nombres>VICTOR</Nombres>
        <FechaNacimiento>1977-04-01</FechaNacimiento>
        <RFC>BECV770401</RFC>
        <CURP/>
        <Nacionalidad>MX</Nacionalidad>
        <Residencia>5</Residencia>
        <EstadoCivil/>
        <Sexo/>
        <ClaveElectorIFE/>
        <NumeroDependientes>0</NumeroDependientes>
        <FechaDefuncion/>
      </Nombre>
      <Domicilios>
        <Domicilio>
          <Direccion>AV CTO EJIDO COLECTIVO</Direccion>
          <ColoniaPoblacion>barr plateros</ColoniaPoblacion>
          <DelegacionMunicipio>CHIMALHUACAN</DelegacionMunicipio>
          <Ciudad>CHIMALHUACAN</Ciudad>
          <Estado>MEX</Estado>
          <CP>56356</CP>
          <FechaResidencia>2021-05-16</FechaResidencia>
          <NumeroTelefono/>
          <TipoDomicilio/>
          <TipoAsentamiento/>
          <FechaRegistroDomicilio>2021-05-16</FechaRegistroDomicilio>
        </Domicilio>
        <Domicilio>
          <Direccion>CTO EJ COLECTIVO 4</Direccion>
          <ColoniaPoblacion>PLATEROS BARRIO</ColoniaPoblacion>
          <DelegacionMunicipio/>
          <Ciudad>CHIMALHUACAN</Ciudad>
          <Estado>MEX</Estado>
          <CP>56358</CP>
          <FechaResidencia>2020-09-27</FechaResidencia>
          <NumeroTelefono/>
          <TipoDomicilio/>
          <TipoAsentamiento>0</TipoAsentamiento>
          <FechaRegistroDomicilio>2020-09-27</FechaRegistroDomicilio>
        </Domicilio>
        <Domicilio>
          <Direccion>AV CIRCUITO EJIDO COLECTIVO MZ 481 LT 41</Direccion>
          <ColoniaPoblacion>PLATEROS</ColoniaPoblacion>
          <DelegacionMunicipio>CHIMALHUACAN</DelegacionMunicipio>
          <Ciudad/>
          <Estado>MEX</Estado>
          <CP>56356</CP>
          <FechaResidencia>2019-10-15</FechaResidencia>
          <NumeroTelefono>5566119187</NumeroTelefono>
          <TipoDomicilio/>
          <TipoAsentamiento>0</TipoAsentamiento>
          <FechaRegistroDomicilio>2019-10-15</FechaRegistroDomicilio>
        </Domicilio>
      </Domicilios>
      <Empleos/>
      <Mensajes>
        <Mensaje>
          <TipoMensaje>20</TipoMensaje>
          <Leyenda>11</Leyenda>
        </Mensaje>
      </Mensajes>
      <Cuentas>
        <Cuenta>
          <FechaActualizacion>2019-05-20</FechaActualizacion>
          <RegistroImpugnado>0</RegistroImpugnado>
          <ClaveOtorgante/>
          <NombreOtorgante>BANCO AZTECA / ELEKTRA</NombreOtorgante>
          <CuentaActual>000121410000428633</CuentaActual>
          <TipoResponsabilidad>I</TipoResponsabilidad>
          <TipoCuenta>F</TipoCuenta>
          <TipoCredito>PP</TipoCredito>
          <ClaveUnidadMonetaria>MX</ClaveUnidadMonetaria>
          <ValorActivoValuacion>9500</ValorActivoValuacion>
          <NumeroPagos>52</NumeroPagos>
          <FrecuenciaPagos>S</FrecuenciaPagos>
          <MontoPagar>0</MontoPagar>
          <FechaAperturaCuenta>2018-11-22</FechaAperturaCuenta>
          <FechaUltimoPago>2019-05-20</FechaUltimoPago>
          <FechaUltimaCompra>2018-11-22</FechaUltimaCompra>
          <FechaCierreCuenta>2019-05-20</FechaCierreCuenta>
          <FechaReporte>2019-05-20</FechaReporte>
          <UltimaFechaSaldoCero/>
          <Garantia/>
          <CreditoMaximo>16848</CreditoMaximo>
          <SaldoActual>0</SaldoActual>
          <LimiteCredito>0</LimiteCredito>
          <SaldoVencido>0</SaldoVencido>
          <NumeroPagosVencidos>0</NumeroPagosVencidos>
          <PagoActual> V</PagoActual>
          <HistoricoPagos> V V V V V V V V V V V V V V V V V V V V V V V V V V</HistoricoPagos>
          <FechaRecienteHistoricoPagos/>
          <FechaAntiguaHistoricoPagos/>
          <ClavePrevencion/>
          <TotalPagosReportados>0</TotalPagosReportados>
          <PeorAtraso>0</PeorAtraso>
          <FechaPeorAtraso/>
          <SaldoVencidoPeorAtraso>0</SaldoVencidoPeorAtraso>
        </Cuenta>
        <Cuenta>
          <FechaActualizacion>2019-05-20</FechaActualizacion>
          <RegistroImpugnado>0</RegistroImpugnado>
          <ClaveOtorgante/>
          <NombreOtorgante>BANCO AZTECA / ELEKTRA</NombreOtorgante>
          <CuentaActual>000121410000428634</CuentaActual>
          <TipoResponsabilidad>I</TipoResponsabilidad>
          <TipoCuenta>F</TipoCuenta>
          <TipoCredito>PP</TipoCredito>
          <ClaveUnidadMonetaria>MX</ClaveUnidadMonetaria>
          <ValorActivoValuacion>839</ValorActivoValuacion>
          <NumeroPagos>52</NumeroPagos>
          <FrecuenciaPagos>S</FrecuenciaPagos>
          <MontoPagar>0</MontoPagar>
          <FechaAperturaCuenta>2018-11-22</FechaAperturaCuenta>
          <FechaUltimoPago>2019-05-20</FechaUltimoPago>
          <FechaUltimaCompra>2018-11-22</FechaUltimaCompra>
          <FechaCierreCuenta>2019-05-20</FechaCierreCuenta>
          <FechaReporte>2019-05-20</FechaReporte>
          <UltimaFechaSaldoCero/>
          <Garantia/>
          <CreditoMaximo>1300</CreditoMaximo>
          <SaldoActual>0</SaldoActual>
          <LimiteCredito>0</LimiteCredito>
          <SaldoVencido>0</SaldoVencido>
          <NumeroPagosVencidos>0</NumeroPagosVencidos>
          <PagoActual> V</PagoActual>
          <HistoricoPagos> V V V V V V V V V V V V V V V V V V V V V V V V V V</HistoricoPagos>
          <FechaRecienteHistoricoPagos/>
          <FechaAntiguaHistoricoPagos/>
          <ClavePrevencion/>
          <TotalPagosReportados>0</TotalPagosReportados>
          <PeorAtraso>0</PeorAtraso>
          <FechaPeorAtraso/>
          <SaldoVencidoPeorAtraso>0</SaldoVencidoPeorAtraso>
        </Cuenta>
        <Cuenta>
          <FechaActualizacion>2019-10-26</FechaActualizacion>
          <RegistroImpugnado>0</RegistroImpugnado>
          <ClaveOtorgante/>
          <NombreOtorgante>BANCO AZTECA / ELEKTRA</NombreOtorgante>
          <CuentaActual>000121410000457176</CuentaActual>
          <TipoResponsabilidad>I</TipoResponsabilidad>
          <TipoCuenta>F</TipoCuenta>
          <TipoCredito>LC</TipoCredito>
          <ClaveUnidadMonetaria>MX</ClaveUnidadMonetaria>
          <ValorActivoValuacion>3777</ValorActivoValuacion>
          <NumeroPagos>13</NumeroPagos>
          <FrecuenciaPagos>S</FrecuenciaPagos>
          <MontoPagar>0</MontoPagar>
          <FechaAperturaCuenta>2019-08-11</FechaAperturaCuenta>
          <FechaUltimoPago>2019-10-26</FechaUltimoPago>
          <FechaUltimaCompra>2019-08-11</FechaUltimaCompra>
          <FechaCierreCuenta>2019-10-26</FechaCierreCuenta>
          <FechaReporte>2019-10-26</FechaReporte>
          <UltimaFechaSaldoCero/>
          <Garantia/>
          <CreditoMaximo>4090</CreditoMaximo>
          <SaldoActual>0</SaldoActual>
          <LimiteCredito>0</LimiteCredito>
          <SaldoVencido>0</SaldoVencido>
          <NumeroPagosVencidos>0</NumeroPagosVencidos>
          <PagoActual> V</PagoActual>
          <HistoricoPagos> V V V V V V V V V V V</HistoricoPagos>
          <FechaRecienteHistoricoPagos/>
          <FechaAntiguaHistoricoPagos/>
          <ClavePrevencion/>
          <TotalPagosReportados>0</TotalPagosReportados>
          <PeorAtraso>0</PeorAtraso>
          <FechaPeorAtraso/>
          <SaldoVencidoPeorAtraso>0</SaldoVencidoPeorAtraso>
        </Cuenta>
        <Cuenta>
          <FechaActualizacion>2020-09-27</FechaActualizacion>
          <RegistroImpugnado>0</RegistroImpugnado>
          <ClaveOtorgante/>
          <NombreOtorgante>BANCO AZTECA / ELEKTRA</NombreOtorgante>
          <CuentaActual>000121410000464232</CuentaActual>
          <TipoResponsabilidad>I</TipoResponsabilidad>
          <TipoCuenta>F</TipoCuenta>
          <TipoCredito>CC</TipoCredito>
          <ClaveUnidadMonetaria>MX</ClaveUnidadMonetaria>
          <ValorActivoValuacion>6270</ValorActivoValuacion>
          <NumeroPagos>48</NumeroPagos>
          <FrecuenciaPagos>S</FrecuenciaPagos>
          <MontoPagar>0</MontoPagar>
          <FechaAperturaCuenta>2019-10-15</FechaAperturaCuenta>
          <FechaUltimoPago>2020-09-27</FechaUltimoPago>
          <FechaUltimaCompra>2019-10-15</FechaUltimaCompra>
          <FechaCierreCuenta>2020-09-27</FechaCierreCuenta>
          <FechaReporte>2020-09-27</FechaReporte>
          <UltimaFechaSaldoCero/>
          <Garantia/>
          <CreditoMaximo>7816</CreditoMaximo>
          <SaldoActual>0</SaldoActual>
          <LimiteCredito>0</LimiteCredito>
          <SaldoVencido>0</SaldoVencido>
          <NumeroPagosVencidos>16</NumeroPagosVencidos>
          <PagoActual> V</PagoActual>
          <HistoricoPagos> V V0201 V0101 V01 V V0201 V0201 V01 V0201 V01 V0201 V V V V V V V V V V V V V V V V V V V01 V V V V</HistoricoPagos>
          <FechaRecienteHistoricoPagos/>
          <FechaAntiguaHistoricoPagos/>
          <ClavePrevencion/>
          <TotalPagosReportados>0</TotalPagosReportados>
          <PeorAtraso>2</PeorAtraso>
          <FechaPeorAtraso>2020-05-12</FechaPeorAtraso>
          <SaldoVencidoPeorAtraso>333</SaldoVencidoPeorAtraso>
        </Cuenta>
        <Cuenta>
          <FechaActualizacion>2020-09-27</FechaActualizacion>
          <RegistroImpugnado>0</RegistroImpugnado>
          <ClaveOtorgante/>
          <NombreOtorgante>BANCO AZTECA / ELEKTRA</NombreOtorgante>
          <CuentaActual>000121410000484532</CuentaActual>
          <TipoResponsabilidad>I</TipoResponsabilidad>
          <TipoCuenta>F</TipoCuenta>
          <TipoCredito>LC</TipoCredito>
          <ClaveUnidadMonetaria>MX</ClaveUnidadMonetaria>
          <ValorActivoValuacion>1078</ValorActivoValuacion>
          <NumeroPagos>26</NumeroPagos>
          <FrecuenciaPagos>S</FrecuenciaPagos>
          <MontoPagar>0</MontoPagar>
          <FechaAperturaCuenta>2020-04-12</FechaAperturaCuenta>
          <FechaUltimoPago>2020-09-27</FechaUltimoPago>
          <FechaUltimaCompra>2020-04-12</FechaUltimaCompra>
          <FechaCierreCuenta>2020-09-27</FechaCierreCuenta>
          <FechaReporte>2020-09-27</FechaReporte>
          <UltimaFechaSaldoCero/>
          <Garantia/>
          <CreditoMaximo>1597</CreditoMaximo>
          <SaldoActual>0</SaldoActual>
          <LimiteCredito>0</LimiteCredito>
          <SaldoVencido>0</SaldoVencido>
          <NumeroPagosVencidos>18</NumeroPagosVencidos>
          <PagoActual> V</PagoActual>
          <HistoricoPagos> V01 V0201 V0101010101 V0201 V02010201030201 V01 V</HistoricoPagos>
          <FechaRecienteHistoricoPagos/>
          <FechaAntiguaHistoricoPagos/>
          <ClavePrevencion/>
          <TotalPagosReportados>0</TotalPagosReportados>
          <PeorAtraso>3</PeorAtraso>
          <FechaPeorAtraso>2020-05-17</FechaPeorAtraso>
          <SaldoVencidoPeorAtraso>190</SaldoVencidoPeorAtraso>
        </Cuenta>
        <Cuenta>
          <FechaActualizacion>2021-05-09</FechaActualizacion>
          <RegistroImpugnado>0</RegistroImpugnado>
          <ClaveOtorgante/>
          <NombreOtorgante>BANCO AZTECA / ELEKTRA</NombreOtorgante>
          <CuentaActual>000121410000503695</CuentaActual>
          <TipoResponsabilidad>I</TipoResponsabilidad>
          <TipoCuenta>F</TipoCuenta>
          <TipoCredito>LC</TipoCredito>
          <ClaveUnidadMonetaria>MX</ClaveUnidadMonetaria>
          <ValorActivoValuacion>500</ValorActivoValuacion>
          <NumeroPagos>52</NumeroPagos>
          <FrecuenciaPagos>S</FrecuenciaPagos>
          <MontoPagar>17</MontoPagar>
          <FechaAperturaCuenta>2020-09-27</FechaAperturaCuenta>
          <FechaUltimoPago>2021-05-09</FechaUltimoPago>
          <FechaUltimaCompra>2020-09-27</FechaUltimaCompra>
          <FechaCierreCuenta/>
          <FechaReporte>2021-05-09</FechaReporte>
          <UltimaFechaSaldoCero/>
          <Garantia/>
          <CreditoMaximo>884</CreditoMaximo>
          <SaldoActual>340</SaldoActual>
          <LimiteCredito>0</LimiteCredito>
          <SaldoVencido>0</SaldoVencido>
          <NumeroPagosVencidos>7</NumeroPagosVencidos>
          <PagoActual> V</PagoActual>
          <HistoricoPagos> V-- V V V V V01 V-------- V V V01 V V V V01 V01 V01 V01 V V V01 V</HistoricoPagos>
          <FechaRecienteHistoricoPagos/>
          <FechaAntiguaHistoricoPagos/>
          <ClavePrevencion/>
          <TotalPagosReportados>0</TotalPagosReportados>
          <PeorAtraso>1</PeorAtraso>
          <FechaPeorAtraso>2020-10-04</FechaPeorAtraso>
          <SaldoVencidoPeorAtraso>17</SaldoVencidoPeorAtraso>
        </Cuenta>
        <Cuenta>
          <FechaActualizacion>2021-05-09</FechaActualizacion>
          <RegistroImpugnado>0</RegistroImpugnado>
          <ClaveOtorgante/>
          <NombreOtorgante>BANCO AZTECA / ELEKTRA</NombreOtorgante>
          <CuentaActual>000121410000518362</CuentaActual>
          <TipoResponsabilidad>I</TipoResponsabilidad>
          <TipoCuenta>F</TipoCuenta>
          <TipoCredito>LC</TipoCredito>
          <ClaveUnidadMonetaria>MX</ClaveUnidadMonetaria>
          <ValorActivoValuacion>16927</ValorActivoValuacion>
          <NumeroPagos>52</NumeroPagos>
          <FrecuenciaPagos>S</FrecuenciaPagos>
          <MontoPagar>257</MontoPagar>
          <FechaAperturaCuenta>2021-01-24</FechaAperturaCuenta>
          <FechaUltimoPago>2021-05-09</FechaUltimoPago>
          <FechaUltimaCompra>2021-01-24</FechaUltimaCompra>
          <FechaCierreCuenta/>
          <FechaReporte>2021-05-09</FechaReporte>
          <UltimaFechaSaldoCero/>
          <Garantia/>
          <CreditoMaximo>13396</CreditoMaximo>
          <SaldoActual>9541</SaldoActual>
          <LimiteCredito>0</LimiteCredito>
          <SaldoVencido>0</SaldoVencido>
          <NumeroPagosVencidos>1</NumeroPagosVencidos>
          <PagoActual> V</PagoActual>
          <HistoricoPagos> V-- V V V V V01 V-------- V V V</HistoricoPagos>
          <FechaRecienteHistoricoPagos/>
          <FechaAntiguaHistoricoPagos/>
          <ClavePrevencion/>
          <TotalPagosReportados>0</TotalPagosReportados>
          <PeorAtraso>1</PeorAtraso>
          <FechaPeorAtraso>2021-03-21</FechaPeorAtraso>
          <SaldoVencidoPeorAtraso>257</SaldoVencidoPeorAtraso>
        </Cuenta>
        <Cuenta>
          <FechaActualizacion>2021-04-18</FechaActualizacion>
          <RegistroImpugnado>0</RegistroImpugnado>
          <ClaveOtorgante/>
          <NombreOtorgante>BANCO AZTECA / ELEKTRA</NombreOtorgante>
          <CuentaActual>4213646160201336</CuentaActual>
          <TipoResponsabilidad>I</TipoResponsabilidad>
          <TipoCuenta>L</TipoCuenta>
          <TipoCredito>CP</TipoCredito>
          <ClaveUnidadMonetaria>MX</ClaveUnidadMonetaria>
          <ValorActivoValuacion>0</ValorActivoValuacion>
          <NumeroPagos>0</NumeroPagos>
          <FrecuenciaPagos>S</FrecuenciaPagos>
          <MontoPagar>241</MontoPagar>
          <FechaAperturaCuenta>2020-09-27</FechaAperturaCuenta>
          <FechaUltimoPago>2021-04-18</FechaUltimoPago>
          <FechaUltimaCompra>2020-09-27</FechaUltimaCompra>
          <FechaCierreCuenta/>
          <FechaReporte>2021-04-18</FechaReporte>
          <UltimaFechaSaldoCero/>
          <Garantia/>
          <CreditoMaximo>5543</CreditoMaximo>
          <SaldoActual>5543</SaldoActual>
          <LimiteCredito>0</LimiteCredito>
          <SaldoVencido>0</SaldoVencido>
          <NumeroPagosVencidos>0</NumeroPagosVencidos>
          <PagoActual> V</PagoActual>
          <HistoricoPagos> V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V</HistoricoPagos>
          <FechaRecienteHistoricoPagos/>
          <FechaAntiguaHistoricoPagos/>
          <ClavePrevencion/>
          <TotalPagosReportados>0</TotalPagosReportados>
          <PeorAtraso>0</PeorAtraso>
          <FechaPeorAtraso/>
          <SaldoVencidoPeorAtraso>0</SaldoVencidoPeorAtraso>
        </Cuenta>
        <Cuenta>
          <FechaActualizacion>2021-05-08</FechaActualizacion>
          <RegistroImpugnado>0</RegistroImpugnado>
          <ClaveOtorgante/>
          <NombreOtorgante>COMUNICACIONES / BC</NombreOtorgante>
          <CuentaActual/>
          <TipoResponsabilidad>I</TipoResponsabilidad>
          <TipoCuenta>L</TipoCuenta>
          <TipoCredito>OT</TipoCredito>
          <ClaveUnidadMonetaria>MX</ClaveUnidadMonetaria>
          <ValorActivoValuacion/>
          <NumeroPagos/>
          <FrecuenciaPagos>M</FrecuenciaPagos>
          <MontoPagar>2303</MontoPagar>
          <FechaAperturaCuenta>2018-10-13</FechaAperturaCuenta>
          <FechaUltimoPago>2019-10-21</FechaUltimoPago>
          <FechaUltimaCompra>2018-10-13</FechaUltimaCompra>
          <FechaCierreCuenta/>
          <FechaReporte>2021-04-30</FechaReporte>
          <UltimaFechaSaldoCero/>
          <Garantia/>
          <CreditoMaximo>6015</CreditoMaximo>
          <SaldoActual>2303</SaldoActual>
          <LimiteCredito/>
          <SaldoVencido>2303</SaldoVencido>
          <NumeroPagosVencidos>9</NumeroPagosVencidos>
          <PagoActual>13</PagoActual>
          <HistoricoPagos>131313131313060606</HistoricoPagos>
          <FechaRecienteHistoricoPagos/>
          <FechaAntiguaHistoricoPagos/>
          <ClavePrevencion/>
          <TotalPagosReportados/>
          <PeorAtraso>13</PeorAtraso>
          <FechaPeorAtraso/>
          <SaldoVencidoPeorAtraso>0</SaldoVencidoPeorAtraso>
        </Cuenta>
        <Cuenta>
          <FechaActualizacion>2021-05-06</FechaActualizacion>
          <RegistroImpugnado>0</RegistroImpugnado>
          <ClaveOtorgante/>
          <NombreOtorgante>COMUNICACIONES / BC</NombreOtorgante>
          <CuentaActual/>
          <TipoResponsabilidad>I</TipoResponsabilidad>
          <TipoCuenta>L</TipoCuenta>
          <TipoCredito>LC</TipoCredito>
          <ClaveUnidadMonetaria>MX</ClaveUnidadMonetaria>
          <ValorActivoValuacion/>
          <NumeroPagos>1</NumeroPagos>
          <FrecuenciaPagos>M</FrecuenciaPagos>
          <MontoPagar>0</MontoPagar>
          <FechaAperturaCuenta>2012-07-10</FechaAperturaCuenta>
          <FechaUltimoPago>2013-04-16</FechaUltimoPago>
          <FechaUltimaCompra>2013-03-28</FechaUltimaCompra>
          <FechaCierreCuenta/>
          <FechaReporte>2021-04-30</FechaReporte>
          <UltimaFechaSaldoCero/>
          <Garantia/>
          <CreditoMaximo>1125</CreditoMaximo>
          <SaldoActual>0</SaldoActual>
          <LimiteCredito/>
          <SaldoVencido>0</SaldoVencido>
          <NumeroPagosVencidos>0</NumeroPagosVencidos>
          <PagoActual> V</PagoActual>
          <HistoricoPagos> V V V V V V V V V V V V V V V V V V V V V V V V V</HistoricoPagos>
          <FechaRecienteHistoricoPagos/>
          <FechaAntiguaHistoricoPagos/>
          <ClavePrevencion/>
          <TotalPagosReportados/>
          <PeorAtraso>00</PeorAtraso>
          <FechaPeorAtraso/>
          <SaldoVencidoPeorAtraso>0</SaldoVencidoPeorAtraso>
        </Cuenta>
        <Cuenta>
          <FechaActualizacion>2019-01-09</FechaActualizacion>
          <RegistroImpugnado>0</RegistroImpugnado>
          <ClaveOtorgante/>
          <NombreOtorgante>COMUNICACIONES / BC</NombreOtorgante>
          <CuentaActual/>
          <TipoResponsabilidad>I</TipoResponsabilidad>
          <TipoCuenta>R</TipoCuenta>
          <TipoCredito>LC</TipoCredito>
          <ClaveUnidadMonetaria>MX</ClaveUnidadMonetaria>
          <ValorActivoValuacion/>
          <NumeroPagos/>
          <FrecuenciaPagos>M</FrecuenciaPagos>
          <MontoPagar>0</MontoPagar>
          <FechaAperturaCuenta>2017-11-15</FechaAperturaCuenta>
          <FechaUltimoPago>2018-10-08</FechaUltimoPago>
          <FechaUltimaCompra>2018-10-13</FechaUltimaCompra>
          <FechaCierreCuenta>2018-12-31</FechaCierreCuenta>
          <FechaReporte>2018-12-31</FechaReporte>
          <UltimaFechaSaldoCero/>
          <Garantia/>
          <CreditoMaximo>1002</CreditoMaximo>
          <SaldoActual>0</SaldoActual>
          <LimiteCredito>597</LimiteCredito>
          <SaldoVencido>0</SaldoVencido>
          <NumeroPagosVencidos>1</NumeroPagosVencidos>
          <PagoActual> V</PagoActual>
          <HistoricoPagos> V V V V V V V V V V V V-- V01 V--</HistoricoPagos>
          <FechaRecienteHistoricoPagos/>
          <FechaAntiguaHistoricoPagos/>
          <ClavePrevencion>CC</ClavePrevencion>
          <TotalPagosReportados/>
          <PeorAtraso>01</PeorAtraso>
          <FechaPeorAtraso/>
          <SaldoVencidoPeorAtraso>0</SaldoVencidoPeorAtraso>
        </Cuenta>
        <Cuenta>
          <FechaActualizacion>2018-03-05</FechaActualizacion>
          <RegistroImpugnado>0</RegistroImpugnado>
          <ClaveOtorgante/>
          <NombreOtorgante>AUTOMOTRIZ / BC</NombreOtorgante>
          <CuentaActual/>
          <TipoResponsabilidad>I</TipoResponsabilidad>
          <TipoCuenta>F</TipoCuenta>
          <TipoCredito>CA</TipoCredito>
          <ClaveUnidadMonetaria>MX</ClaveUnidadMonetaria>
          <ValorActivoValuacion/>
          <NumeroPagos>36</NumeroPagos>
          <FrecuenciaPagos>M</FrecuenciaPagos>
          <MontoPagar>0</MontoPagar>
          <FechaAperturaCuenta>2015-02-17</FechaAperturaCuenta>
          <FechaUltimoPago>2018-02-15</FechaUltimoPago>
          <FechaUltimaCompra>2015-02-17</FechaUltimaCompra>
          <FechaCierreCuenta>2018-02-15</FechaCierreCuenta>
          <FechaReporte>2018-02-28</FechaReporte>
          <UltimaFechaSaldoCero/>
          <Garantia/>
          <CreditoMaximo>6827</CreditoMaximo>
          <SaldoActual>0</SaldoActual>
          <LimiteCredito>234320</LimiteCredito>
          <SaldoVencido>0</SaldoVencido>
          <NumeroPagosVencidos>0</NumeroPagosVencidos>
          <PagoActual> V</PagoActual>
          <HistoricoPagos> V V V V V V V V V V V V V V V V V V V V V V V V V</HistoricoPagos>
          <FechaRecienteHistoricoPagos/>
          <FechaAntiguaHistoricoPagos/>
          <ClavePrevencion>CC</ClavePrevencion>
          <TotalPagosReportados/>
          <PeorAtraso>00</PeorAtraso>
          <FechaPeorAtraso/>
          <SaldoVencidoPeorAtraso>0</SaldoVencidoPeorAtraso>
        </Cuenta>
      </Cuentas>
      <ConsultasEfectuadas>
        <ConsultaEfectuada>
          <FechaConsulta>2021-05-16</FechaConsulta>
          <ClaveOtorgante/>
          <NombreOtorgante>BANCO AZTECA</NombreOtorgante>
          <TelefonoOtorgante>17207000</TelefonoOtorgante>
          <TipoCredito>F</TipoCredito>
          <ClaveUnidadMonetaria>MX</ClaveUnidadMonetaria>
          <ImporteCredito>0</ImporteCredito>
          <TipoResponsabilidad/>
        </ConsultaEfectuada>
        <ConsultaEfectuada>
          <FechaConsulta>2021-01-03</FechaConsulta>
          <ClaveOtorgante/>
          <NombreOtorgante>SIC</NombreOtorgante>
          <TipoCredito>F</TipoCredito>
          <ClaveUnidadMonetaria>MX</ClaveUnidadMonetaria>
          <ImporteCredito>0</ImporteCredito>
          <TipoResponsabilidad/>
        </ConsultaEfectuada>
        <ConsultaEfectuada>
          <FechaConsulta>2020-03-07</FechaConsulta>
          <ClaveOtorgante/>
          <NombreOtorgante>BANCO AZTECA</NombreOtorgante>
          <TipoCredito>F</TipoCredito>
          <ClaveUnidadMonetaria>MX</ClaveUnidadMonetaria>
          <ImporteCredito>0</ImporteCredito>
          <TipoResponsabilidad/>
        </ConsultaEfectuada>
        <ConsultaEfectuada>
          <FechaConsulta>2019-10-15</FechaConsulta>
          <ClaveOtorgante/>
          <NombreOtorgante>TELEFONIA CELULAR</NombreOtorgante>
          <TipoCredito>F</TipoCredito>
          <ClaveUnidadMonetaria>MX</ClaveUnidadMonetaria>
          <ImporteCredito>0</ImporteCredito>
          <TipoResponsabilidad/>
        </ConsultaEfectuada>
        <ConsultaEfectuada>
          <FechaConsulta>2021-01-03</FechaConsulta>
          <ClaveOtorgante/>
          <NombreOtorgante>FINANCIERA / BC</NombreOtorgante>
          <TipoCredito>TC</TipoCredito>
          <ClaveUnidadMonetaria/>
          <ImporteCredito>0</ImporteCredito>
          <TipoResponsabilidad>I</TipoResponsabilidad>
        </ConsultaEfectuada>
        <ConsultaEfectuada>
          <FechaConsulta>2020-06-12</FechaConsulta>
          <ClaveOtorgante/>
          <NombreOtorgante>BANCO / BC</NombreOtorgante>
          <TipoCredito>TC</TipoCredito>
          <ClaveUnidadMonetaria/>
          <ImporteCredito>0</ImporteCredito>
          <TipoResponsabilidad>I</TipoResponsabilidad>
        </ConsultaEfectuada>
        <ConsultaEfectuada>
          <FechaConsulta>2020-04-03</FechaConsulta>
          <ClaveOtorgante/>
          <NombreOtorgante>BANCO / BC</NombreOtorgante>
          <TipoCredito>TC</TipoCredito>
          <ClaveUnidadMonetaria/>
          <ImporteCredito>0</ImporteCredito>
          <TipoResponsabilidad>I</TipoResponsabilidad>
        </ConsultaEfectuada>
        <ConsultaEfectuada>
          <FechaConsulta>2020-01-28</FechaConsulta>
          <ClaveOtorgante/>
          <NombreOtorgante>BANCO / BC</NombreOtorgante>
          <TipoCredito>TC</TipoCredito>
          <ClaveUnidadMonetaria/>
          <ImporteCredito>0</ImporteCredito>
          <TipoResponsabilidad>I</TipoResponsabilidad>
        </ConsultaEfectuada>
        <ConsultaEfectuada>
          <FechaConsulta>2019-12-01</FechaConsulta>
          <ClaveOtorgante/>
          <NombreOtorgante>BANCO / BC</NombreOtorgante>
          <TipoCredito>TC</TipoCredito>
          <ClaveUnidadMonetaria/>
          <ImporteCredito>0</ImporteCredito>
          <TipoResponsabilidad>I</TipoResponsabilidad>
        </ConsultaEfectuada>
        <ConsultaEfectuada>
          <FechaConsulta>2019-07-05</FechaConsulta>
          <ClaveOtorgante/>
          <NombreOtorgante>BANCO / BC</NombreOtorgante>
          <TipoCredito>TC</TipoCredito>
          <ClaveUnidadMonetaria/>
          <ImporteCredito>0</ImporteCredito>
          <TipoResponsabilidad>I</TipoResponsabilidad>
        </ConsultaEfectuada>
        <ConsultaEfectuada>
          <FechaConsulta>2019-06-08</FechaConsulta>
          <ClaveOtorgante/>
          <NombreOtorgante>COMUNICACIONES / BC</NombreOtorgante>
          <TipoCredito>TC</TipoCredito>
          <ClaveUnidadMonetaria/>
          <ImporteCredito>0</ImporteCredito>
          <TipoResponsabilidad>I</TipoResponsabilidad>
        </ConsultaEfectuada>
        <ConsultaEfectuada>
          <FechaConsulta>2019-05-17</FechaConsulta>
          <ClaveOtorgante/>
          <NombreOtorgante>AUTOMOTRIZ / BC</NombreOtorgante>
          <TipoCredito>CA</TipoCredito>
          <ClaveUnidadMonetaria/>
          <ImporteCredito>0</ImporteCredito>
          <TipoResponsabilidad>I</TipoResponsabilidad>
        </ConsultaEfectuada>
      </ConsultasEfectuadas>
      <DeclaracionesConsumidor/>
      <Scores>
        <Score>
          <NombreScore>FICO</NombreScore>
          <Codigo>140</Codigo>
          <Valor>594</Valor>
          <Razon1>D8</Razon1>
          <Razon2>K0</Razon2>
          <Razon3>P9</Razon3>
          <Razon4>E0</Razon4>
          <Error>0</Error>
        </Score>
      </Scores>
    </Persona>
  </Personas>
</Respuesta>'''